name: Build and Release Tauri App

on:
  pull_request:
    paths:
      - 'dbbs-faculty-match/**'
      - '.github/workflows/packaging.yml'
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to build and release'
        required: true

jobs:
  build:
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact-suffix: windows_x64
          - os: macos-13
            artifact-suffix: macos_x64
          - os: macos-latest
            artifact-suffix: macos_arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: dbbs-faculty-match/package-lock.json

      - name: Install frontend dependencies
        working-directory: dbbs-faculty-match
        run: npm ci

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Use short Cargo target dir (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $short = "D:\a\t"
          New-Item -ItemType Directory -Force -Path $short | Out-Null
          "CARGO_TARGET_DIR=$short" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "Using CARGO_TARGET_DIR=$short"

      - name: Ensure NSIS is installed/up to date
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco upgrade nsis -y --no-progress
          $refresh = Join-Path $env:ChocolateyInstall 'bin/RefreshEnv.cmd'
          if (Test-Path $refresh) {
            & $refresh | Out-Null
          }

          $candidateDirs = @()
          if ($env:ProgramFiles) {
            $candidateDirs += (Join-Path $env:ProgramFiles 'NSIS')
          }
          if (${env:ProgramFiles(x86)}) {
            $candidateDirs += (Join-Path ${env:ProgramFiles(x86)} 'NSIS')
          }
          if ($env:ChocolateyInstall) {
            $candidateDirs += Get-ChildItem -Path (Join-Path $env:ChocolateyInstall 'lib') -Directory -Filter 'nsis*' |
              Sort-Object LastWriteTime -Descending |
              ForEach-Object { Join-Path $_.FullName 'tools' }
          }

          foreach ($dir in $candidateDirs | Where-Object { $_ -and (Test-Path $_) }) {
            if (Test-Path (Join-Path $dir 'makensis.exe')) {
              $dir | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
              Write-Host "Added $dir to PATH"
              break
            }
          }

      - name: Verify makensis works
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $command = Get-Command makensis -ErrorAction SilentlyContinue
          if (-not $command) {
            $candidates = @()
            if ($env:ProgramFiles) {
              $candidates += (Join-Path $env:ProgramFiles 'NSIS/makensis.exe')
            }
            if (${env:ProgramFiles(x86)}) {
              $candidates += (Join-Path ${env:ProgramFiles(x86)} 'NSIS/makensis.exe')
            }
            if ($env:ChocolateyInstall) {
              $candidates += Get-ChildItem -Path (Join-Path $env:ChocolateyInstall 'lib') -Directory -Filter 'nsis*' |
                Sort-Object LastWriteTime -Descending |
                ForEach-Object { Join-Path $_.FullName 'tools/makensis.exe' }
            }

            foreach ($candidate in $candidates | Where-Object { $_ -and (Test-Path $_) }) {
              $command = Get-Item $candidate
              break
            }
          }

          if (-not $command) {
            throw 'makensis executable not found after installing NSIS'
          }

          $exePath = if ($command -is [System.Management.Automation.CommandInfo]) { $command.Source } else { $command.FullName }
          & $exePath /VERSION



      - name: Build Tauri application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: dbbs-faculty-match

  create-release:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      release-id: ${{ steps.create-release.outputs.id }}
      release-tag: ${{ steps.release-tag.outputs.value }}
    steps:
      - name: Determine release tag
        id: release-tag
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == 'workflow_dispatch' ]]; then
            echo "value=${{ inputs.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "value=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Create GitHub release
        id: create-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ steps.release-tag.outputs.value }}
        shell: bash
        run: |
          set -euo pipefail

          repo="${{ github.repository }}"
          release_tag="${RELEASE_TAG}"
          release_name="DDBS Reviewer Recommendations v${release_tag}"
          payload=$(jq -n \
            --arg tag "$release_tag" \
            --arg name "$release_name" \
            --arg target "${{ github.sha }}" \
            '{tag_name:$tag, name:$name, target_commitish:$target, draft:false, prerelease:false, body:""}')

          response_file=$(mktemp)
          if gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              "repos/${repo}/releases" \
              --input - \
              >"$response_file" <<<"$payload"; then
            :
          else
            if gh api \
                -H "Accept: application/vnd.github+json" \
                "repos/${repo}/releases/tags/${release_tag}" \
                >"$response_file"; then
              :
            else
              echo "Failed to create or retrieve release for tag ${release_tag}" >&2
              cat "$response_file" >&2 || true
              exit 1
            fi
          fi

          release_id=$(jq -r '.id // empty' "$response_file")
          if [[ -z "$release_id" ]]; then
            echo "Could not determine release id" >&2
            cat "$response_file" >&2 || true
            exit 1
          fi

          rm -f "$response_file"

          echo "id=$release_id" >> "$GITHUB_OUTPUT"

  release:
    needs: create-release
    if: needs.create-release.result == 'success'
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact-suffix: windows_x64
          - os: macos-13
            artifact-suffix: macos_x64
          - os: macos-latest
            artifact-suffix: macos_arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: dbbs-faculty-match/package-lock.json

      - name: Install frontend dependencies
        working-directory: dbbs-faculty-match
        run: npm ci
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Read app metadata
        id: metadata
        shell: bash
        working-directory: dbbs-faculty-match
        run: |
          set -euo pipefail
          slug=$(jq -r '.name' package.json)
          version=$(jq -r '.version' src-tauri/tauri.conf.json)
          echo "slug=${slug}" >>"$GITHUB_OUTPUT"
          echo "version=${version}" >>"$GITHUB_OUTPUT"

      - name: Use short Cargo target dir (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $short = "D:\a\t"
          New-Item -ItemType Directory -Force -Path $short | Out-Null
          "CARGO_TARGET_DIR=$short" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "Using CARGO_TARGET_DIR=$short"

      - name: Ensure NSIS is installed/up to date
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco upgrade nsis -y --no-progress
          $refresh = Join-Path $env:ChocolateyInstall 'bin/RefreshEnv.cmd'
          if (Test-Path $refresh) {
            & $refresh | Out-Null
          }

          $candidateDirs = @()
          if ($env:ProgramFiles) {
            $candidateDirs += (Join-Path $env:ProgramFiles 'NSIS')
          }
          if (${env:ProgramFiles(x86)}) {
            $candidateDirs += (Join-Path ${env:ProgramFiles(x86)} 'NSIS')
          }
          if ($env:ChocolateyInstall) {
            $candidateDirs += Get-ChildItem -Path (Join-Path $env:ChocolateyInstall 'lib') -Directory -Filter 'nsis*' |
              Sort-Object LastWriteTime -Descending |
              ForEach-Object { Join-Path $_.FullName 'tools' }
          }

          foreach ($dir in $candidateDirs | Where-Object { $_ -and (Test-Path $_) }) {
            if (Test-Path (Join-Path $dir 'makensis.exe')) {
              $dir | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
              Write-Host "Added $dir to PATH"
              break
            }
          }

      - name: Verify makensis works
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $command = Get-Command makensis -ErrorAction SilentlyContinue
          if (-not $command) {
            $candidates = @()
            if ($env:ProgramFiles) {
              $candidates += (Join-Path $env:ProgramFiles 'NSIS/makensis.exe')
            }
            if (${env:ProgramFiles(x86)}) {
              $candidates += (Join-Path ${env:ProgramFiles(x86)} 'NSIS/makensis.exe')
            }
            if ($env:ChocolateyInstall) {
              $candidates += Get-ChildItem -Path (Join-Path $env:ChocolateyInstall 'lib') -Directory -Filter 'nsis*' |
                Sort-Object LastWriteTime -Descending |
                ForEach-Object { Join-Path $_.FullName 'tools/makensis.exe' }
            }

            foreach ($candidate in $candidates | Where-Object { $_ -and (Test-Path $_) }) {
              $command = Get-Item $candidate
              break
            }
          }

          if (-not $command) {
            throw 'makensis executable not found after installing NSIS'
          }

          $exePath = if ($command -is [System.Management.Automation.CommandInfo]) { $command.Source } else { $command.FullName }
          & $exePath /VERSION

      - name: Build Tauri application
        working-directory: dbbs-faculty-match
        run: npm exec -- tauri build --ci
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}

      - name: Rename Windows installer
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $bundleDir = if ($env:CARGO_TARGET_DIR) { Join-Path $env:CARGO_TARGET_DIR 'release\bundle\nsis' } else { 'dbbs-faculty-match\src-tauri\target\release\bundle\nsis' }
          if (-not (Test-Path $bundleDir)) { throw "Bundle directory not found: $bundleDir" }
          $installer = Get-ChildItem -Path $bundleDir -Filter '*.exe' | Select-Object -First 1
          if (-not $installer) { throw "NSIS installer not found in $bundleDir" }
          $newName = "${{ steps.metadata.outputs.slug }}_${{ steps.metadata.outputs.version }}_${{ matrix.artifact-suffix }}.exe"
          Rename-Item -Path $installer.FullName -NewName $newName -Force


      - name: Rename macOS disk image
        if: runner.os == 'macOS'
        shell: bash
        run: |
          set -euo pipefail
          bundle_dir="dbbs-faculty-match/src-tauri/target/release/bundle/dmg"
          dmg=$(find "$bundle_dir" -maxdepth 1 -type f -name '*.dmg' | head -n 1)
          if [[ -z "$dmg" ]]; then
            echo "No DMG artifact found" >&2
            exit 1
          fi
          new_name="${{ steps.metadata.outputs.slug }}_${{ steps.metadata.outputs.version }}_${{ matrix.artifact-suffix }}.dmg"
          mv "$dmg" "$(dirname "$dmg")/$new_name"

      - name: Upload release artifacts
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ needs.create-release.outputs.release-tag }}
        run: |
          set -euo pipefail
          base_dir="dbbs-faculty-match/src-tauri/target/release/bundle"
          if [[ ! -d "$base_dir" ]]; then
            echo "Bundle directory not found: $base_dir" >&2
            exit 1
          fi
          while IFS= read -r -d '' file; do
            echo "Uploading $file"
            gh release upload "$RELEASE_TAG" "$file" --clobber
          done < <(find "$base_dir" -type f \( -name '*.exe' -o -name '*.zip' -o -name '*.dmg' -o -name '*.pkg' -o -name '*.app' -o -name '*.tar.gz' -o -name '*.msix' -o -name '*.json' \) -print0)
